
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tanya
 */
public class Gshop extends javax.swing.JFrame {

      
Connection con;
void opencon(){
    try{
    Class.forName("java.sql.Driver");
    con=DriverManager.getConnection("jdbc:mysql://localhost/shopcart","root","pass");
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
}
void display(){
    try{
        String a1=(String)cmb1.getSelectedItem();
        String q="Select * from cart"+a1;
        Statement stmt=con.createStatement();
        ResultSet rs=stmt.executeQuery(q);
        DefaultTableModel dtm=(DefaultTableModel) tbl.getModel();
        while(dtm.getRowCount()>0)
            dtm.removeRow(0);
       String a,b,c,d,e;
        while(rs.next()){
          a=rs.getString(1);
          b=rs.getString(2);
          c=rs.getString(3);
          d=rs.getString(4);
          e=rs.getString(5);
          Object nr[]={a,b,c,d,e};
          dtm.addRow(nr);
        }
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
}
void combo(){
    try{
        cmb1.removeAllItems();
       int a1=Integer.parseInt(lb.getText());
       String ab="Select count(gid) from groupmember where mid="+a1;
       Statement st=con.createStatement();
       ResultSet rs1=st.executeQuery(ab);
       rs1.next();
       int n1=rs1.getInt(1);
       String a="Select gid from groupmember where mid="+a1;
       
       ResultSet rs=st.executeQuery(a);
       rs.next();
       while(n1!=0){
       cmb1.addItem(rs.getString(1));
       n1--;
       rs.next();
               }
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
}
void display1(){
    try{
        String a1=(String)cmb1.getSelectedItem();
        String z=(String)cat.getSelectedItem( );
        String q="Select * from cart"+a1+" where category='"+z+"'";
        Statement stmt=con.createStatement();
        ResultSet rs=stmt.executeQuery(q);
        DefaultTableModel dtm=(DefaultTableModel) tbl.getModel();
        while(dtm.getRowCount()>0)
            dtm.removeRow(0);
       String a,b,c,d,e;
        while(rs.next()){
          a=rs.getString(1);
          b=rs.getString(2);
          c=rs.getString(3);
          d=rs.getString(4);
          e=rs.getString(5);
          Object nr[]={a,b,c,d,e};
          dtm.addRow(nr);
        }
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
}
    
    
    /**
     * Creates new form Gshop
     */
    public Gshop(int a) {
        initComponents();
        cat.setVisible(false);
        lb.setVisible(false);
        lb.setText(Integer.toString(a));
        lb1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        sc = new javax.swing.JCheckBox();
        cat = new javax.swing.JComboBox<>();
        exit = new javax.swing.JButton();
        lb = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        cmb1 = new javax.swing.JComboBox<>();
        shp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ItemName", "Quantity", "Unit", "Category", "Bought"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        tbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 60, 840, 280);

        sc.setText("Shop By Category");
        sc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scActionPerformed(evt);
            }
        });
        getContentPane().add(sc);
        sc.setBounds(40, 400, 149, 25);

        cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fruits and Vegetables", "Stationery", "Dairy Products", "Packaged Product", "Toiletries" }));
        cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catActionPerformed(evt);
            }
        });
        getContentPane().add(cat);
        cat.setBounds(220, 400, 154, 22);

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(50, 530, 133, 25);

        lb.setText("jLabel1");
        getContentPane().add(lb);
        lb.setBounds(314, 437, 41, 0);
        getContentPane().add(lb1);
        lb1.setBounds(703, 398, 0, 0);

        cmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmb1);
        cmb1.setBounds(220, 460, 150, 22);

        shp.setText("SHOP");
        shp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shpActionPerformed(evt);
            }
        });
        getContentPane().add(shp);
        shp.setBounds(230, 530, 126, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tanya\\Downloads\\wr\\fruitbasket.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(560, 390, 290, 200);

        jLabel2.setText("YOUR GROUPS:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 470, 120, 16);

        jLabel3.setText("CLICK ON ALL THE ITEMS YOU BUY AND WHEN DONE, PRESS SHOP.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 20, 430, 16);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 970, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scActionPerformed
        // TODO add your handling code here:
        if(sc.isSelected()){
        cat.setVisible(true);
       // opencon();
        display1();}
        else{
            cat.setVisible(false);
       // opencon();
        display();
        }
    }//GEN-LAST:event_scActionPerformed

    private void catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catActionPerformed
        // TODO add your handling code here:
        //opencon();
        display1();
    }//GEN-LAST:event_catActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        opencon();
        
         combo();
        display();
      
    }//GEN-LAST:event_formWindowOpened

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int a1=Integer.parseInt(lb.getText());
        
         shop s1=new shop(a1);
            s1.setVisible(true);
            s1.setSize(950,650);
       
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void cmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb1ActionPerformed
        // TODO add your handling code here:
        if(sc.isSelected()){
        cat.setVisible(true);
       
        display1();}
        else{
            cat.setVisible(false);
      
        display();
        }
    }//GEN-LAST:event_cmb1ActionPerformed

    private void tblKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblKeyReleased

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        try{
        if(tbl.getSelectedRow()!=-1){
           String a=tbl.getValueAt(tbl.getSelectedRow(), 0).toString();
            String a1=(String)cmb1.getSelectedItem();
            String q="select bought from cart"+a1+" where items='"+a+"'";
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(q);
            rs.next();
            if(rs.getString(1).equals("No")){
                String q1="update cart"+a1+" set bought='Yes' where items='"+a+"'";
                stmt.executeUpdate(q1);
            }else{
                String q2="update cart"+a1+" set bought='No' where items='"+a+"'";
                stmt.executeUpdate(q2);
            }
            if(sc.isSelected()){
                display1();
            }
            else{
                display();
            }
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_tblMouseClicked

    private void shpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shpActionPerformed
        // TODO add your handling code here:
    try{
         String a1=(String)cmb1.getSelectedItem();
        String q="Select * from cart"+a1+" where bought='Yes'";
        Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(q);
             String a,c,d,e,q1;
           int b;
            while(rs.next()){
               
                a=rs.getString(1);
                b=rs.getInt(2);
                c=rs.getString(3);
                d=rs.getString(4);
                
               // e=rs.getString(5);
                q1="Insert into histcart"+a1+" values('"+a+"',"+b+",'"+c+"','"+d+"')";
                 Statement stmt1=con.createStatement();
               
                stmt1.executeUpdate(q1);
               
            }
            String q2="delete from cart"+a1+" where bought='Yes'";
            stmt.executeUpdate(q2);
            if(sc.isSelected()){
                display1();
            }
            else{
                display();
            }
          
    }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
    }//GEN-LAST:event_shpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             // new Gshop(13).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cat;
    private javax.swing.JComboBox<String> cmb1;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb1;
    private javax.swing.JCheckBox sc;
    private javax.swing.JButton shp;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
