
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tanya
 */
public class history extends javax.swing.JFrame {
    
Connection con;
void opencon(){
    try{
    Class.forName("java.sql.Driver");
    con=DriverManager.getConnection("jdbc:mysql://localhost/shopcart","root","pass");
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
}

void combo(){
    try{
        cmb1.removeAllItems();
       int a1=Integer.parseInt(lb.getText());
       String ab="Select count(gid) from groupmember where mid="+a1;
       Statement st=con.createStatement();
       ResultSet rs1=st.executeQuery(ab);
       rs1.next();
       int n1=rs1.getInt(1);
       String a="Select gid from groupmember where mid="+a1;
       
       ResultSet rs=st.executeQuery(a);
       rs.next();
       while(n1!=0){
       cmb1.addItem(rs.getString(1));
       n1--;
       rs.next();
               }
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
}
void display(){
    try{
        String a1=(String)cmb1.getSelectedItem();
        String q="Select * from histcart"+a1;
        Statement stmt=con.createStatement();
        ResultSet rs=stmt.executeQuery(q);
        DefaultTableModel dtm=(DefaultTableModel) tbl.getModel();
        while(dtm.getRowCount()>0)
            dtm.removeRow(0);
       String a,b,c,d;
        while(rs.next()){
          a=rs.getString(1);
          b=rs.getString(2);
          c=rs.getString(3);
          d=rs.getString(4);
          Object nr[]={a,b,c,d};
          dtm.addRow(nr);
        }
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
}
    /**
     * Creates new form history
     */
    public history(String a) {
        initComponents();
         lb.setVisible(false);
        lb.setText(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        back = new javax.swing.JButton();
        cmb1 = new javax.swing.JComboBox<>();
        lb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ITEMS", "QUANTITY", "UNIT", "CATEGORY"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(35, 26, 875, 380);

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(625, 574, 176, 25);

        cmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmb1);
        cmb1.setBounds(225, 575, 186, 22);
        getContentPane().add(lb);
        lb.setBounds(588, 578, 0, 0);

        jLabel1.setText("YOUR GROUPS:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 578, 143, 16);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tanya\\Downloads\\wr\\shoplist.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 410, 190, 190);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-20, -10, 1010, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        opencon();
        combo();
        display();
    }//GEN-LAST:event_formWindowOpened

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         int a1=Integer.parseInt(lb.getText());
        shop s=new shop(a1);
        s.setVisible(true);
        s.setSize(950,650);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void cmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb1ActionPerformed
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_cmb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new history().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> cmb1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
