
import java.sql.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tanya
 */
public class login extends javax.swing.JFrame {
Connection con;

    void opencon(){
    try{
    Class.forName("java.sql.Driver");
    con=DriverManager.getConnection("jdbc:mysql://localhost/shopcart","root","pass");
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
}

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        enter = new javax.swing.JButton();
        chk = new javax.swing.JCheckBox();
        signup = new javax.swing.JButton();
        quit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("MID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 120, 98, 25);
        getContentPane().add(mid);
        mid.setBounds(380, 110, 195, 38);

        jLabel2.setText("PASSWORD:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 210, 98, 25);
        getContentPane().add(pass);
        pass.setBounds(380, 200, 195, 37);

        enter.setText("ENTER");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        getContentPane().add(enter);
        enter.setBounds(210, 420, 167, 40);

        chk.setText("SHOW PASSWORD");
        chk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkActionPerformed(evt);
            }
        });
        getContentPane().add(chk);
        chk.setBounds(380, 260, 140, 25);

        signup.setText("SIGN UP");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup);
        signup.setBounds(480, 420, 192, 40);

        quit.setText("QUIT");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        getContentPane().add(quit);
        quit.setBounds(340, 510, 167, 40);

        jLabel3.setFont(new java.awt.Font("Verdana Pro SemiBold", 3, 24)); // NOI18N
        jLabel3.setText("LOGIN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 30, 190, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tanya\\Downloads\\wr\\login.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 70, 220, 210);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tanya\\Downloads\\wr\\login1.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(650, 40, 230, 230);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 990, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkActionPerformed
        // TODO add your handling code here:
        if(chk.isSelected()){
            pass.setEchoChar((char)0);
        }
        else{
            pass.setEchoChar('*');
        }
       
    }//GEN-LAST:event_chkActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        
        signup s1=new signup();
                s1.setVisible(true);
                s1.setSize(950,650);
        dispose();
    }//GEN-LAST:event_signupActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // TODO add your handling code here:
        
        try{
            int n=Integer.parseInt(mid.getText());
        String p=pass.getText();
       String a="Select password,groupexists from totalmembers where mid="+n;
     //  String a="select password from totalmembers";
       
        Statement s=con.createStatement();
        
        ResultSet rs=s.executeQuery(a);
        rs.next();
       
        String a1,a2;
        a1=rs.getString(1);
         
        a2=rs.getString(2);
        
        if(p.equals(a1)){
            
            if(a2=="N"){
            Group g=new Group(Integer.toString(n));
            g.setVisible(true);
            g.setSize(950,650);
            }
            else{
                shop s1=new shop(n);
                s1.setVisible(true);
                s1.setSize(950,650);
            }
        }
        else{
            mid.setText("");
            pass.setText("");
            JOptionPane.showMessageDialog(this,"Incorrect password.");
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        dispose();
    }//GEN-LAST:event_enterActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        opencon();
    }//GEN-LAST:event_formWindowOpened

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 login s=new login();
        s.setVisible(true);
        s.setSize(950,650);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chk;
    private javax.swing.JButton enter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField mid;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton quit;
    private javax.swing.JButton signup;
    // End of variables declaration//GEN-END:variables
}
