
import java.sql.*;
//import java.sql.ResultSet;
//import java.sql.Statement;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tanya
 */
public class Members1 extends javax.swing.JFrame {
    Connection con;
    void opencon(){
    try{
    Class.forName("java.sql.Driver");
    con=DriverManager.getConnection("jdbc:mysql://localhost/shopcart","root","pass");
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
}

void combo(){
    try{
        cmb1.removeAllItems();
       int a1=Integer.parseInt(lb.getText());
       String ab="Select count(gid) from groupmember where mid="+a1;
       Statement st=con.createStatement();
       ResultSet rs1=st.executeQuery(ab);
       rs1.next();
       int n1=rs1.getInt(1);
       String a="Select gid from groupmember where mid="+a1;
       
       ResultSet rs=st.executeQuery(a);
       rs.next();
       while(n1!=0){
       cmb1.addItem(rs.getString(1));
       n1--;
       rs.next();
               }
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
}
void display(){
    try{
        String a1=(String)cmb1.getSelectedItem();
         String q="Select mid,mname from totalmembers natural join groupmember where gid='"+a1+"'";
        
        Statement stmt=con.createStatement();
        ResultSet rs=stmt.executeQuery(q);
        DefaultTableModel dtm=(DefaultTableModel) tbl.getModel();
        while(dtm.getRowCount()>0)
            dtm.removeRow(0);
        int c;
       String a;
        while(rs.next()){
          a=rs.getString(2);
        
          c=rs.getInt(1);
          Object nr[]={c,a};
          dtm.addRow(nr);
          String q1="select admin from groups where gid="+a1;
           Statement stmt1=con.createStatement();
          
          ResultSet rs1=stmt1.executeQuery(q1);
          rs1.next();
          
          lb2.setText(rs1.getString(1));
        }
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    }}

    /**
     * Creates new form Members1
     */
    public Members1(int a) {
        initComponents();
        lb.setText(Integer.toString(a));
        lb.setVisible(false);
        lb2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        cmb1 = new javax.swing.JComboBox<>();
        lb = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        leave = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "M ID", "Member Name"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(62, 35, 816, 162);

        cmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmb1);
        cmb1.setBounds(460, 483, 135, 22);
        getContentPane().add(lb);
        lb.setBounds(833, 358, 0, 0);
        getContentPane().add(lb2);
        lb2.setBounds(819, 373, 0, 0);

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(613, 554, 150, 25);

        jLabel1.setText("YOUR GROUPS:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(336, 489, 97, 16);

        leave.setText("LEAVE GROUP");
        leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveActionPerformed(evt);
            }
        });
        getContentPane().add(leave);
        leave.setBounds(382, 554, 150, 25);

        remove.setText("REMOVE  A MEMBER");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        getContentPane().add(remove);
        remove.setBounds(151, 554, 150, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tanya\\Downloads\\wr\\members.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 270, 293, 163);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 970, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        opencon();
        combo();
        display();
    }//GEN-LAST:event_formWindowOpened

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
            shop g=new shop(Integer.parseInt(lb.getText()));
        g.setVisible(true);
        g.setSize(950,650);
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void cmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb1ActionPerformed
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_cmb1ActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
        String grp=(String)cmb1.getSelectedItem();
        if(lb2.getText().equals(lb.getText())){
             try{
                 
           
                 
        String a=JOptionPane.showInputDialog("Enter MemberID to be deleted");
        if(a.equals(lb.getText())){
            JOptionPane.showMessageDialog(this,"You cannot remove yourself. However, you can leave the group.");
        }
        else{
         String q="select count(*) from groupmember where mid='"+a+"' and gid='"+grp+"'";
   Statement s=con.createStatement();
        ResultSet rs=s.executeQuery(q);
        rs.next();
        int no=rs.getInt(1);
        if(no==1){
        String q1="delete from groupmember where mid='"+a+"' and gid='"+grp+"'";
        s.executeUpdate(q1);
        display();
        }
        
            
        
        else{
            JOptionPane.showMessageDialog(this,"This member does not belong to this group.");
        }
        }}catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        }
        else{
            JOptionPane.showMessageDialog(this,"You are not an Admin. This acton is not allowed.");
        
        }
    }//GEN-LAST:event_removeActionPerformed

    private void leaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveActionPerformed
        // TODO add your handling code here:
         int a1=Integer.parseInt(lb.getText());
         String grp=(String)cmb1.getSelectedItem();
         if(lb2.getText().equals(lb.getText())){
          
           
           try{
            String sq="select count(gid) from groupmember where gid='"+grp+"'";
            Statement s=con.createStatement();
        ResultSet rs3=s.executeQuery(sq);
        rs3.next();
        int sq1=rs3.getInt(1);
            if(sq1==1){
              int asd=JOptionPane.showConfirmDialog(this, "Do you want the group to be deleted?");
              if(asd==0){
                String q1="delete from groupmember where mid='"+a1+"' and gid='"+grp+"'";
        s.executeUpdate(q1);
         String q2="delete from groups where gid='"+grp+"'";
        s.executeUpdate(q2);
        String q3="select count(gid) from groupmember where mid='"+a1+"'";
        Statement s1=con.createStatement();
        ResultSet rs1=s1.executeQuery(q3);
        rs1.next();
        if(rs1.getInt(1)==0){
            String q4="update totalmembers set groupexists='N' where mid='"+a1+"'";
            s.executeUpdate(q4);
            Group g=new Group(Integer.toString(a1));
         g.setVisible(true);
         g.setSize(950,650);
         dispose();
        }
        else{
            combo();
        display();
        
        }    
                  
                  
                  
              }
            }
            else{
       String a=JOptionPane.showInputDialog("Enter Member ID to be new Admin.");
       if(a.equals(a1)){
           JOptionPane.showMessageDialog(this,"You have entered your ID.");
       }
       else{
   //    String q1="select mgroup from totalmembers where mid='"+a+"'";
   String q="select count(*) from groupmember where mid='"+a+"' and gid='"+grp+"'";
  Statement s2=con.createStatement();
        ResultSet rs=s2.executeQuery(q);
        rs.next();
        int no=rs.getInt(1);
        if(no==1){
            String q1="delete from groupmember where mid='"+a1+"' and gid='"+grp+"'";
        s.executeUpdate(q1);
        String q2="update groups set admin='"+a+"' where gid='"+grp+"'";
        s.executeUpdate(q2);
        String q3="select count(gid) from groupmember where mid='"+a1+"'";
        Statement s3=con.createStatement();
        ResultSet rs1=s3.executeQuery(q3);
        rs1.next();
        if(rs1.getInt(1)==0){
            String q4="update totalmembers set groupexists='N' where mid='"+a1+"'";
            s.executeUpdate(q4);
            Group g=new Group(Integer.toString(a1));
         g.setVisible(true);
         g.setSize(950,650);
         dispose();
        }else{
            combo();
             display();
        }
        } 
        
        else{
             JOptionPane.showMessageDialog(this,"This member does not belong to this group.");
        }
        }}}catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }  
           
           
        }
        else{
         try{
                  
             String q1="delete from groupmember where mid='"+a1+"' and gid='"+grp+"'";
        Statement s=con.createStatement();
        s.executeUpdate(q1);
        display();
           }
           catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        }
    }//GEN-LAST:event_leaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Members1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Members1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Members1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Members1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Members1(6).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb1;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb2;
    private javax.swing.JButton leave;
    private javax.swing.JButton remove;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
