
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tanya
 */
public class resetpass extends javax.swing.JFrame {
          
Connection con;
void opencon(){
    try{
    Class.forName("java.sql.Driver");
    con=DriverManager.getConnection("jdbc:mysql://localhost/shopcart","root","pass");
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
}
void combo(){
    try{
        cmb1.removeAllItems();
       int a1=Integer.parseInt(lb.getText());
       String ab="Select count(gid) from groupmember where mid="+a1;
       Statement st=con.createStatement();
       ResultSet rs1=st.executeQuery(ab);
       rs1.next();
       int n1=rs1.getInt(1);
       String a="Select gid from groupmember where mid="+a1;
       
       ResultSet rs=st.executeQuery(a);
       rs.next();
       while(n1!=0){
       cmb1.addItem(rs.getString(1));
       n1--;
       rs.next();
               }
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
}

    /**
     * Creates new form resetpass
     */
    public resetpass(int a) {
        initComponents();
        lb.setVisible(false);
        lb.setText(Integer.toString(a));
        lb1.setVisible(false);
        lb1.setText("N"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rpass = new javax.swing.JPasswordField();
        back = new javax.swing.JButton();
        cmb1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(lb);
        lb.setBounds(478, 215, 0, 0);
        getContentPane().add(lb1);
        lb1.setBounds(299, 41, 154, 36);

        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(100, 430, 270, 25);

        jLabel2.setText("ENTER PASSWORD:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 160, 125, 37);
        getContentPane().add(rpass);
        rpass.setBounds(220, 160, 180, 37);

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(100, 510, 270, 25);

        cmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmb1);
        cmb1.setBounds(230, 340, 140, 22);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        jLabel1.setText("RESET PASSWORD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 60, 230, 29);

        jLabel3.setText("YOUR GROUP:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 340, 110, 16);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tanya\\Downloads\\wr\\reset.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(580, 180, 250, 340);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -30, 990, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        opencon();
        combo();
        try{
            String q="select admin from groups where gid='"+cmb1.getSelectedItem()+"'";
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(q);
            rs.next();
            int ab=rs.getInt(1);
            if(ab==Integer.parseInt(lb.getText())){
               lb1.setText("Y"); 
            }
            else{
                lb1.setText("N"); 
            }
        }
        catch(Exception e){
    JOptionPane.showMessageDialog(this,e.getMessage());
            }
    }//GEN-LAST:event_formWindowOpened

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        if(lb1.getText().equals("Y")){
           
          try{
            String a1=(String) cmb1.getSelectedItem();
            
            String a=rpass.getText();
        String q="update groups set gpassword='"+a+"' where gid='"+a1+"'";
       
        Statement s=con.createStatement();
        s.executeUpdate(q);
      rpass.setText("");
       JOptionPane.showMessageDialog(this,"Password successfully updated.");
      
        }catch(Exception e){
    JOptionPane.showMessageDialog(this,e.getMessage());
            }  
        }
        else{
            rpass.setText("");
            JOptionPane.showMessageDialog(this,"Not an admin for the selected group.");
        }
    }//GEN-LAST:event_resetActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        int a=Integer.parseInt(lb.getText());
         shop s=new shop(a);
        s.setVisible(true);
        s.setSize(950,650);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void cmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb1ActionPerformed
        // TODO add your handling code here:
      try{
            String q="select admin from groups where gid='"+cmb1.getSelectedItem()+"'";
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(q);
            rs.next();
            int ab=rs.getInt(1);
            if(ab==Integer.parseInt(lb.getText())){
               lb1.setText("Y"); 
            }
            else{
                lb1.setText("N"); 
            }
        }
        catch(Exception e){
    JOptionPane.showMessageDialog(this,e.getMessage());
            }
    }//GEN-LAST:event_cmb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() { 
            public void run() {
              // new resetpass(13).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> cmb1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb1;
    private javax.swing.JButton reset;
    private javax.swing.JPasswordField rpass;
    // End of variables declaration//GEN-END:variables
}
