
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tanya
 */
public class shop extends javax.swing.JFrame {
Connection con;
void opencon(){
    try{
    Class.forName("java.sql.Driver");
    con=DriverManager.getConnection("jdbc:mysql://localhost/shopcart","root","pass");
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
}
    /**
     * Creates new form shop
     */
    public shop(int a) {
        initComponents();
        lb.setVisible(false);
        lb.setText(Integer.toString(a));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        goshop = new javax.swing.JButton();
        viewshoplist = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        viewmemberslist = new javax.swing.JButton();
        lb = new javax.swing.JLabel();
        rgp = new javax.swing.JButton();
        chng = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        goshop.setText(" GO SHOPPING!");
        goshop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goshopActionPerformed(evt);
            }
        });
        getContentPane().add(goshop);
        goshop.setBounds(330, 150, 240, 25);

        viewshoplist.setText("VIEW SHOPPING LIST");
        viewshoplist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewshoplistActionPerformed(evt);
            }
        });
        getContentPane().add(viewshoplist);
        viewshoplist.setBounds(330, 210, 240, 25);

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(330, 510, 240, 25);

        viewmemberslist.setText("VIEW MEMBERS");
        viewmemberslist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewmemberslistActionPerformed(evt);
            }
        });
        getContentPane().add(viewmemberslist);
        viewmemberslist.setBounds(330, 270, 240, 25);
        getContentPane().add(lb);
        lb.setBounds(277, 74, 23, 0);

        rgp.setText("GROUP SETTINGS");
        rgp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgpActionPerformed(evt);
            }
        });
        getContentPane().add(rgp);
        rgp.setBounds(330, 330, 240, 25);

        chng.setText("EDIT GROUP");
        chng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chngActionPerformed(evt);
            }
        });
        getContentPane().add(chng);
        chng.setBounds(330, 390, 240, 25);

        jButton1.setText("SHOPPING HISTORY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 450, 240, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tanya\\Downloads\\wr\\fulltrolley.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 180, 250, 330);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tanya\\Downloads\\wr\\gs.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(640, 210, 240, 290);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -10, 970, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void viewshoplistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewshoplistActionPerformed
        // TODO add your handling code here:
    int a1=Integer.parseInt(lb.getText());
    tanya t=new tanya(a1);
    t.setVisible(true);
    t.setSize(950,650);
    dispose();
    }//GEN-LAST:event_viewshoplistActionPerformed

    private void goshopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goshopActionPerformed
        // TODO add your handling code here:
        int a1=Integer.parseInt(lb.getText());
       // try{
        //String q="Select mgroup from totalmembers where mid="+a1;
        //Statement s=con.createStatement();
       // ResultSet rs=s.executeQuery(q);
        //rs.next();
        //int a2=rs.getInt(1);
        
        Gshop g=new Gshop(a1);
        g.setVisible(true);
        g.setSize(950,650);
        dispose();
    //catch(Exception e){
    //JOptionPane.showMessageDialog(this,e.getMessage());

    }//GEN-LAST:event_goshopActionPerformed

    private void viewmemberslistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewmemberslistActionPerformed
        // TODO add your handling code here:
        int a1=Integer.parseInt(lb.getText());
        Members1 g=new Members1(a1);
        g.setVisible(true);
        g.setSize(950,650);
        dispose();
    }//GEN-LAST:event_viewmemberslistActionPerformed

    private void rgpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgpActionPerformed
        // TODO add your handling code here:
        int a1=Integer.parseInt(lb.getText());
       // System.out.println(a1);
        try{
      /*  String q="select admin from totalmembers where mid="+a1;
        Statement s=con.createStatement();
        ResultSet rs=s.executeQuery(q);
        rs.next();
        String n=rs.getString(1);
        if(n.equalsIgnoreCase("No")){
            JOptionPane.showMessageDialog(this,"Not an admin. Cannot proceed.");
        }
        else{*/
       
        resetpass g=new resetpass(a1);
        g.setVisible(true);
        g.setSize(950,650);
        dispose();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_rgpActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        opencon();
    }//GEN-LAST:event_formWindowOpened

    private void chngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chngActionPerformed
        // TODO add your handling code here:
        String a1=lb.getText();
         Group g=new Group(a1);
        g.setVisible(true);
        g.setSize(950,650);
            dispose();
    }//GEN-LAST:event_chngActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          String a1=lb.getText();
        
          history g=new history(a1);
        g.setVisible(true);
        g.setSize(950,650);
            dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new shop(5).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chng;
    private javax.swing.JButton exit;
    private javax.swing.JButton goshop;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb;
    private javax.swing.JButton rgp;
    private javax.swing.JButton viewmemberslist;
    private javax.swing.JButton viewshoplist;
    // End of variables declaration//GEN-END:variables
}
