
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tanya
 */
public class tanya extends javax.swing.JFrame {
    
Connection con;
void opencon(){
    try{
    Class.forName("java.sql.Driver");
    con=DriverManager.getConnection("jdbc:mysql://localhost/shopcart","root","pass");
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
}

void combo(){
    try{
        cmb1.removeAllItems();
       int a1=Integer.parseInt(lb.getText());
       String ab="Select count(gid) from groupmember where mid="+a1;
       Statement st=con.createStatement();
       ResultSet rs1=st.executeQuery(ab);
       rs1.next();
       int n1=rs1.getInt(1);
       String a="Select gid from groupmember where mid="+a1;
       
       ResultSet rs=st.executeQuery(a);
       rs.next();
       while(n1!=0){
       cmb1.addItem(rs.getString(1));
       n1--;
       rs.next();
               }
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
}
void display(){
    try{
        String a1=(String)cmb1.getSelectedItem();
        String q="Select * from cart"+a1;
        Statement stmt=con.createStatement();
        ResultSet rs=stmt.executeQuery(q);
        DefaultTableModel dtm=(DefaultTableModel) tbl.getModel();
        while(dtm.getRowCount()>0)
            dtm.removeRow(0);
       String a,b,c,d;
        while(rs.next()){
          a=rs.getString(1);
          b=rs.getString(2);
          c=rs.getString(3);
          d=rs.getString(4);
          Object nr[]={a,b,c,d};
          dtm.addRow(nr);
        }
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
}
    /**
     * Creates new form tanya
     */
    public tanya(int a) {
        initComponents();
       lbupdate.setVisible(false);
       lb.setVisible(false);
       lb1.setVisible(false);
       lb.setText(Integer.toString(a));
       done.setVisible(false);
       done.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        unit = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        item = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cat = new javax.swing.JComboBox<>();
        lb1 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        lbupdate = new javax.swing.JLabel();
        done = new javax.swing.JButton();
        cmb1 = new javax.swing.JComboBox<>();
        lbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("ITEM:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 90, 56, 16);

        jLabel2.setText("QUANTITY:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(99, 176, 82, 16);

        jLabel4.setText("UNIT:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 270, 82, 16);

        unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitActionPerformed(evt);
            }
        });
        getContentPane().add(unit);
        unit.setBounds(230, 260, 150, 30);

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        getContentPane().add(quantity);
        quantity.setBounds(230, 170, 150, 30);

        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActionPerformed(evt);
            }
        });
        getContentPane().add(item);
        item.setBounds(230, 80, 150, 30);

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(450, 70, 210, 25);

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(680, 70, 200, 25);

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(680, 110, 200, 25);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ITEM", "QUANTITY", "UNIT", "CATEGORY"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 420, 860, 170);

        jLabel3.setText("CATEGORY:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 330, 80, 16);

        cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fruits and Vegetables", "Stationery", "Dairy Products", "Packaged Product", "Toiletries" }));
        getContentPane().add(cat);
        cat.setBounds(230, 330, 170, 22);
        getContentPane().add(lb1);
        lb1.setBounds(820, 300, 0, 0);
        getContentPane().add(lb);
        lb.setBounds(820, 470, 0, 0);

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(450, 110, 210, 25);

        lbupdate.setText("MAKE THE CHANGES AND PRESS DONE.");
        getContentPane().add(lbupdate);
        lbupdate.setBounds(40, 30, 290, 16);

        done.setText("DONE");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        getContentPane().add(done);
        done.setBounds(450, 160, 210, 25);

        cmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmb1);
        cmb1.setBounds(670, 190, 190, 22);

        lbl.setText("YOUR GROUPS:");
        getContentPane().add(lbl);
        lbl.setBounds(530, 190, 110, 16);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tanya\\Downloads\\wr\\baskettt.jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 180, 280, 220);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 960, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed

    }//GEN-LAST:event_quantityActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
       try{
        int a=Integer.parseInt(quantity.getText());
        String b=item.getText();
        String c=unit.getText();
        String d=(String)cat.getSelectedItem( );
        String a1=(String)cmb1.getSelectedItem();
        String e="insert into cart"+a1+" values('"+b+"',"+a+",'"+c+"','"+d+"','No')";
        Statement s=con.createStatement();
        s.executeUpdate(e);
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
       item.setText("");
       unit.setText("");
       quantity.setText("");
        display();
        
    }//GEN-LAST:event_addActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        opencon();
        
       combo();
        display();
    }//GEN-LAST:event_formWindowOpened

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
        String a=JOptionPane.showInputDialog("Enter Item to be deleted");
        String a1=(String)cmb1.getSelectedItem();
        String q="delete from cart"+a1+" where items='"+a+"'";
        Statement s=con.createStatement();
        s.executeUpdate(q);
        display();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
       int a1=Integer.parseInt(lb.getText());
          shop s1=new shop(a1);
            s1.setVisible(true);
            s1.setSize(950,650);
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        lbupdate.setVisible(true);
        add.setVisible(false);
        lbl.setVisible(false);
        cmb1.setVisible(false);
        cmb1.setEnabled(false);
        add.setEnabled(false);
        delete.setVisible(false);
        delete.setEnabled(false);
        exit.setVisible(false);
        exit.setEnabled(false);
       done.setVisible(true);
       done.setEnabled(true);
        try{
        String a=JOptionPane.showInputDialog("Enter Item to be updated");
        String a1=(String)cmb1.getSelectedItem();
        String q1="select * from cart"+a1+" where items='"+a+"'";
        Statement s=con.createStatement();
        ResultSet rs=s.executeQuery(q1);
        rs.next();
        item.setText(rs.getString(1));
        quantity.setText(Integer.toString(rs.getInt(2)));
        unit.setText(rs.getString(3));
        cat.setSelectedItem(rs.getString(4));
       // String q="update cart"+a1+" set where items='"+a+"'";
        //Statement s=con.createStatement();
       // s.executeUpdate(q);
        //display();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_updateActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
        lbupdate.setVisible(false);
        add.setVisible(true);
        add.setEnabled(true);
        delete.setVisible(true);
        delete.setEnabled(true);
        exit.setVisible(true);
        exit.setEnabled(true);
        lbl.setVisible(true);
        cmb1.setVisible(true);
        cmb1.setEnabled(true);
       
        try{
            
            int a=Integer.parseInt(quantity.getText());
        String b=item.getText();
        String c=unit.getText();
        String d=(String)cat.getSelectedItem( );
         String a1=(String)cmb1.getSelectedItem();
        String q="update cart"+a1+" set unit='"+c+"',quantity="+a+",category='"+d+"' where items='"+b+"'";
        Statement s=con.createStatement();
        s.executeUpdate(q);
        display();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
         done.setVisible(false);
        done.setEnabled(false);
         item.setText("");
       unit.setText("");
       quantity.setText("");
    }//GEN-LAST:event_doneActionPerformed

    private void itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemActionPerformed

    private void unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitActionPerformed

    private void cmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb1ActionPerformed
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_cmb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tanya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tanya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tanya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tanya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           //   new tanya(3).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cat;
    private javax.swing.JComboBox<String> cmb1;
    private javax.swing.JButton delete;
    private javax.swing.JButton done;
    private javax.swing.JButton exit;
    private javax.swing.JTextField item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbupdate;
    private javax.swing.JTextField quantity;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField unit;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
